version: "3.8"

services:
  peer1:
    build: ./
    environment:
      LOCAL_NODE: 10.10.1.1
      NGH_ADDR: 10.10.1.2
      UID: "m1"
    networks:
      vpcbr:
        ipv4_address: 10.10.1.1
    tty: true

  peer2:
    build: ./
    environment:
      LOCAL_NODE: 10.10.1.2
      NGH_ADDR: 10.10.1.1
      UID: "m2"
    networks:
      vpcbr:
        ipv4_address: 10.10.1.2
    tty: true
  peer3:
    build: ./
    environment:
      LOCAL_NODE: 10.10.1.3
      NGH_ADDR: 10.10.1.2
      UID: "m3"
    networks:
      vpcbr:
        ipv4_address: 10.10.1.3
    tty: true
  peer4:
    build: ./
    environment:
      LOCAL_NODE: 10.10.1.4
      NGH_ADDR: 10.10.1.2
      UID: "m3"
    networks:
      vpcbr:
        ipv4_address: 10.10.1.4
    tty: true
  peer5:
    build: ./
    environment:
      LOCAL_NODE: 10.10.1.5
      NGH_ADDR: 10.10.1.4
      UID: "m3"
    networks:
      vpcbr:
        ipv4_address: 10.10.1.5
    tty: true
  peer6:
    build: ./
    environment:
      LOCAL_NODE: 10.10.1.6
      NGH_ADDR: 10.10.1.4
      UID: "m6"
    networks:
      vpcbr:
        ipv4_address: 10.10.1.6
    tty: true
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
