// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: proto/p2p.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2PNetwork_NeighbourList_FullMethodName = "/P2PNetwork/NeighbourList"
	P2PNetwork_PeerRegist_FullMethodName    = "/P2PNetwork/PeerRegist"
)

// P2PNetworkClient is the client API for P2PNetwork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type P2PNetworkClient interface {
	NeighbourList(ctx context.Context, in *NeighbourListRequest, opts ...grpc.CallOption) (*NeighbourListResponse, error)
	PeerRegist(ctx context.Context, in *PeerRegistRequest, opts ...grpc.CallOption) (*PeerRegistResponse, error)
}

type p2PNetworkClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PNetworkClient(cc grpc.ClientConnInterface) P2PNetworkClient {
	return &p2PNetworkClient{cc}
}

func (c *p2PNetworkClient) NeighbourList(ctx context.Context, in *NeighbourListRequest, opts ...grpc.CallOption) (*NeighbourListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NeighbourListResponse)
	err := c.cc.Invoke(ctx, P2PNetwork_NeighbourList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNetworkClient) PeerRegist(ctx context.Context, in *PeerRegistRequest, opts ...grpc.CallOption) (*PeerRegistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerRegistResponse)
	err := c.cc.Invoke(ctx, P2PNetwork_PeerRegist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// P2PNetworkServer is the server API for P2PNetwork service.
// All implementations must embed UnimplementedP2PNetworkServer
// for forward compatibility.
type P2PNetworkServer interface {
	NeighbourList(context.Context, *NeighbourListRequest) (*NeighbourListResponse, error)
	PeerRegist(context.Context, *PeerRegistRequest) (*PeerRegistResponse, error)
	mustEmbedUnimplementedP2PNetworkServer()
}

// UnimplementedP2PNetworkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PNetworkServer struct{}

func (UnimplementedP2PNetworkServer) NeighbourList(context.Context, *NeighbourListRequest) (*NeighbourListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NeighbourList not implemented")
}
func (UnimplementedP2PNetworkServer) PeerRegist(context.Context, *PeerRegistRequest) (*PeerRegistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeerRegist not implemented")
}
func (UnimplementedP2PNetworkServer) mustEmbedUnimplementedP2PNetworkServer() {}
func (UnimplementedP2PNetworkServer) testEmbeddedByValue()                    {}

// UnsafeP2PNetworkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PNetworkServer will
// result in compilation errors.
type UnsafeP2PNetworkServer interface {
	mustEmbedUnimplementedP2PNetworkServer()
}

func RegisterP2PNetworkServer(s grpc.ServiceRegistrar, srv P2PNetworkServer) {
	// If the following call pancis, it indicates UnimplementedP2PNetworkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2PNetwork_ServiceDesc, srv)
}

func _P2PNetwork_NeighbourList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeighbourListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNetworkServer).NeighbourList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNetwork_NeighbourList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNetworkServer).NeighbourList(ctx, req.(*NeighbourListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNetwork_PeerRegist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRegistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNetworkServer).PeerRegist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNetwork_PeerRegist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNetworkServer).PeerRegist(ctx, req.(*PeerRegistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// P2PNetwork_ServiceDesc is the grpc.ServiceDesc for P2PNetwork service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PNetwork_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "P2PNetwork",
	HandlerType: (*P2PNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NeighbourList",
			Handler:    _P2PNetwork_NeighbourList_Handler,
		},
		{
			MethodName: "PeerRegist",
			Handler:    _P2PNetwork_PeerRegist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/p2p.proto",
}
